SET dynamodb.throughput.read.percent=READ_PERCENTAGE;

-- S3 target destination
CREATE EXTERNAL TABLE IF NOT EXISTS `s3_TABLENAME` (item MAP<STRING, STRING>)
STORED AS PARQUET
LOCATION 's3://S3_BUCKET/NO_MMYY/'
TBLPROPERTIES ("PARQUET.COMPRESS"="SNAPPY");

INSERT OVERWRITE TABLE `s3_TABLENAME`
SELECT *
FROM `hive_TABLENAME`;

DROP TABLE `hive_TABLENAME`;
